version: '3'
services:
  app:
    image: gradle
    command: sh -c "gradle test --info" 
    volumes:
    - .:/code
    working_dir: /code
    extra_hosts:
    - "service.localhost:192.168.0.105"
    links:
    - appium
    depends_on:
    - appium
  appium:
    image: budtmo/docker-android-x86-9.0
    ports:
    - 6080:6080
    - 5554:5554
    - 5555:5555
    environment:
    - DEVICE="Samsung Galaxy S6"
    volumes:
    - .:/code
  
